package com.burialsociety.member_service.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
public class MemberRequestDto {
    // We only include fields the client should provide.
    // 'id' and 'creationDate' are generated by the server.

    @Size(max = 255, message = "Case number cannot exceed 255 characters")
    private String caseNumber;

    @NotEmpty(message = "Created by is required")
    @Size(max = 255, message = "Created by cannot exceed 255 characters")
    private String createdBy;

    @NotNull(message = "Personal details are required")
    @Valid // <-- This tells Spring to validate the nested DTO
    private PersonalDetailsRequestDto personalDetails;

}
